/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"Inter"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        bg: 'rgb(var(--bg) / <alpha-value>)',
        'bg-secondary': 'rgb(var(--bg-secondary) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--surface-elevated) / <alpha-value>)',
        'surface-interactive': 'rgb(var(--surface-interactive) / <alpha-value>)',
        'surface-highlight': 'rgb(var(--surface-highlight) / <alpha-value>)',
        'text-primary': 'rgb(var(--text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--text-secondary) / <alpha-value>)',
        'text-tertiary': 'rgb(var(--text-tertiary) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
        'border-subtle': 'rgb(var(--border-subtle) / <alpha-value>)',
        'border-luminous': 'rgb(var(--border-luminous) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover) / <alpha-value>)',
        'accent-subtle': 'rgb(var(--accent-subtle) / <alpha-value>)',
        'accent-glow': 'rgb(var(--accent-glow) / <alpha-value>)',
        positive: 'rgb(var(--positive) / <alpha-value>)',
        'positive-glow': 'rgb(var(--positive-glow) / <alpha-value>)',
        negative: 'rgb(var(--negative) / <alpha-value>)',
        'negative-glow': 'rgb(var(--negative-glow) / <alpha-value>)',
        warning: 'rgb(var(--warning) / <alpha-value>)',
        'warning-glow': 'rgb(var(--warning-glow) / <alpha-value>)',
        gold: 'rgb(var(--gold) / <alpha-value>)',
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '10px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
      },
      spacing: {
        '4.5': '1.125rem',
        '13': '3.25rem',
        '18': '4.5rem',
        '22': '5.5rem',
      },
      fontSize: {
        'display': ['2.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h1': ['2rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h2': ['1.5rem', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '600' }],
        'h3': ['1.25rem', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'card-lg': ['1.625rem', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '600' }],
        'label': ['0.6875rem', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '500' }],
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        premium: 'cubic-bezier(0.22, 1, 0.36, 1)',
        gentle: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        micro: '120ms',
        standard: '220ms',
        structural: '320ms',
        cinematic: '700ms',
      },
      maxWidth: {
        'vault': '1440px',
        'content': '1280px',
      },
      boxShadow: {
        'subtle': '0 1px 2px 0 rgb(0 0 0 / 0.04)',
        'soft': '0 2px 8px -2px rgb(0 0 0 / 0.08), 0 4px 16px -4px rgb(0 0 0 / 0.06)',
        'elevated': '0 4px 24px -6px rgb(0 0 0 / 0.12), 0 8px 40px -12px rgb(0 0 0 / 0.08)',
        'lift': '0 8px 40px -12px rgb(0 0 0 / 0.16)',
        'dark-soft': '0 2px 12px -2px rgb(0 0 0 / 0.3), 0 4px 24px -8px rgb(0 0 0 / 0.2)',
        'dark-elevated': '0 4px 32px -8px rgb(0 0 0 / 0.4), 0 12px 48px -16px rgb(0 0 0 / 0.3)',
        'accent': '0 0 0 1px rgb(var(--accent) / 0.2), 0 2px 12px -2px rgb(var(--accent-glow) / 0.15)',
        'accent-hover': '0 0 0 1px rgb(var(--accent) / 0.3), 0 4px 20px -4px rgb(var(--accent-glow) / 0.25), 0 0 32px -8px rgb(var(--accent-glow) / 0.15)',
        'positive-soft': '0 2px 12px -4px rgb(var(--positive-glow) / 0.12)',
        'negative-soft': '0 2px 12px -4px rgb(var(--negative-glow) / 0.12)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-down': {
          from: { opacity: '0', transform: 'translateY(-12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-right': {
          from: { opacity: '0', transform: 'translateX(24px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-left': {
          from: { opacity: '0', transform: 'translateX(-24px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'shimmer': {
          '100%': { transform: 'translateX(100%)' },
        },
        'seal-complete': {
          '0%': { transform: 'scale(1)' },
          '40%': { transform: 'scale(1.08)' },
          '100%': { transform: 'scale(1)' },
        },
        'draw-line': {
          from: { strokeDashoffset: '1000' },
          to: { strokeDashoffset: '0' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.95)', opacity: '0.6' },
          '50%': { transform: 'scale(1.05)', opacity: '0.2' },
          '100%': { transform: 'scale(0.95)', opacity: '0.6' },
        },
        'endpoint-breathe': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.1' },
        },
      },
      animation: {
        'fade-in': 'fade-in 200ms cubic-bezier(0.4, 0, 0.2, 1)',
        'fade-up': 'fade-up 400ms cubic-bezier(0.22, 1, 0.36, 1)',
        'fade-down': 'fade-down 300ms cubic-bezier(0.22, 1, 0.36, 1)',
        'slide-right': 'slide-right 300ms cubic-bezier(0.22, 1, 0.36, 1)',
        'slide-left': 'slide-left 300ms cubic-bezier(0.22, 1, 0.36, 1)',
        'scale-in': 'scale-in 220ms cubic-bezier(0.22, 1, 0.36, 1)',
        'shimmer': 'shimmer 1.6s infinite',
        'seal-complete': 'seal-complete 500ms cubic-bezier(0.22, 1, 0.36, 1)',
        'draw-line': 'draw-line 1.2s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'pulse-ring': 'pulse-ring 3s ease-in-out infinite',
        'endpoint-breathe': 'endpoint-breathe 2.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
